// tests/provider.verify.test.js
import { Verifier } from "@pact-foundation/pact";
import { beforeAll, afterAll, test } from "@jest/globals";
import app, { resetData } from "../src/provider.js"; //  Express app + helper

const PORT = 3000;
const baseUrl = `http://localhost:${PORT}`;
let server;

beforeAll(async () => {
    // Start real provider API
    resetData(); // ensure a known starting state (ids 1 & 2 exist)
    await new Promise((resolve) => { server = app.listen(PORT, resolve); });
});

afterAll(async () => {
    // Cleanly stop the server so Jest exits
    await new Promise((resolve) => server.close(resolve));
});

test(
    "verifies provider against consumer contracts",
    async () => {
        // Check if Pact Broker environment variables are set
        //if (!process.env.PACT_BROKER_BASE_URL || !process.env.PACT_BROKER_TOKEN) {
          //  throw new Error(
            //    "Missing Pact Broker environment variables. Please set:\n" +
              //  "PACT_BROKER_BASE_URL=https://your-workspace.pactflow.io\n" +
                //"PACT_BROKER_TOKEN=your-read-write-token"
           // );
        //}

        const opts = {
            // MUST match the names in your pact JSON generated by your tests:
            // consumer: 'ItemsConsumer', provider: 'ItemsCrudAPI'
            provider: "ItemsCrudAPI",
            providerBaseUrl: baseUrl,

            // Choose ONE of the following two sources for contracts:

            // (A) From a Broker (PactFlow / self-hosted)
            pactBrokerUrl: process.env.PACT_BROKER_BASE_URL,      // e.g. https://<workspace>.pactflow.io
            pactBrokerToken: process.env.PACT_BROKER_TOKEN,       // read/write token
            consumerVersionSelectors: [{ branch: "main", latest: true }], // match how you published

            // (B) Or from a local pact file (uncomment to use local file instead of a broker)
             pactUrls: ["./pacts/ItemsConsumer-ItemsCrudAPI.json"],

            // Publish verification result back to the Broker (ignored if using pactUrls)
            publishVerificationResult: true,
            providerVersion: process.env.GIT_SHA || "local",
            providerBranch: "main",

            // Provider States: keys MUST EXACTLY match your .given("...") strings
            stateHandlers: {
                // Your default resetData() already satisfies these:
                "items exist": async () => { resetData(); },

                "the item for that id exists": async () => { resetData(); },
                "an item with that id exists and can be replaced": async () => { resetData(); },

                // For “does not exist” we also just reset (ids are 1 & 2 only)
                "an item does not exist for the specified id": async () => { resetData(); },

                // Validation scenarios typically need no data setup:
                "a name is provided for the item that needs to be added": async () => {},
                "no name is given when a new item is created": async () => {},
            },

            // If provider needed auth headers during verification, inject them here:
            // requestFilter: (req, res, next) => {
            //   req.headers["authorization"] = "Bearer testtoken";
            //   next();
            // },
        };

        await new Verifier(opts).verifyProvider();
    },
    60_000 // give the verifier time
);
